DROP DATABASE IF EXISTS EBayDB;
CREATE DATABASE EBayDB;

USE EBayDB;

CREATE TABLE ItemInformation(
  id INT NOT NULL AUTO_INCREMENT,
  item VARCHAR(255) NOT NULL,
  min_cost FLOAT(20) NOT NULL,
  curr_bid FLOAT(20) NOT NULL,
  ends_in INT NOT NULL,
  item_image VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);